
stages:
  - dryrun
  - commit

.prep_container: &prep_container
  - pip install oyaml

dryrun:
  image: ${DOCKER_REPO}/${RUNNER_IMAGE}
  stage: dryrun
  script:
    - *prep_container
    - python scripts/provision.py --dryrun --debug

commit:
  image: ${DOCKER_REPO}/${RUNNER_IMAGE}
  stage: commit
  only:
    - master
  script:
    - *prep_container
    - python scripts/provision.py --debug
