
stages:
  - dryrun
  - commit
  - test

.prep_container: &prep_container
  - pip install oyaml

dryrun:
  image: ${DOCKER_REPO}/${RUNNER_IMAGE}
  stage: dryrun
  script:
    - *prep_container
    - python scripts/provision.py --dryrun --debug

commit:
  image: ${DOCKER_REPO}/${RUNNER_IMAGE}
  stage: commit
  only:
    - master
    # - test
  script:
    - *prep_container
    - python scripts/provision.py --debug

test:
  image: ${DOCKER_REPO}/${RUNNER_IMAGE}
  stage: test
  script:
    - echo 'test to be done'

# last step in the pipeline to report status
# using CI_JOB_STATUS requires a more modern gitlab runner as in my lab
# using webhook instead
#notify:
#  image: ${DOCKER_REPO}/${RUNNER_IMAGE}
#  stage: .post
#  script:
#    - pip install webexteamssdk
#    # assumes teams token is provided in environment variable
#    # WEBEX_API_NOTIFICATION_TOKEN
#    - python scripts/notify.py "Pipeline result $CI_JOB_STATUS ($CI_JOB_URL)"
