
nso:
  host: https://oli-test-w.bwi-stf.lab:8888
  username: admin
  password: C1sco123!

service:
  path: l2vpn
  key: customer-id

notify:
  # can specify room_id and/or WebexTeams person email
  #room_id:
  persons:
    - oboehmer@cisco.com

